name: publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run test

  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm install
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Insert repository owner as scope into package name
        run: |
          node <<EOF
          const fs = require('fs').promises;
          fs.readFile('package.json', 'utf8').then((data) => JSON.parse(data)).then((json) => {
            json.name = '@$(echo "$GITHUB_REPOSITORY" | sed 's/\/.\+//')/' + json.name;
            console.info('Package name changed to %s', json.name);
            return fs.writeFile('package.json', JSON.stringify(json), 'utf8');
          }).catch(error => {
            console.error(error);
            process.exit(1);
          });
          EOF
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
